### PR TITLE
Fix scaling of curvature estimate in adapted_grid

### LINKED ISSUE #50: Jagged Plot for a simple function
Heya,
This code:
```
using Plots
gr()
g = x -> 2 + 0.25 * x^-2
plot(g,1,30)
```
Produces this plot for me:
image

Where it looks like the plotting chooses too few plotpoints. 
For e.g. `g = x-> 1 + 0.25 * x^-2` the plot is much better, see
image

### PR DESCRIPTION
**Pull request by yha**
Scale the curvature estimates by `max(f)-min(f)` rather than `max(f)`, which makes the algorithm invariant to shifts in `f`, and fixes the behavior for functions far from zeros relative to their variance.

e.g., `plot( (plot(x->sin(x)+a, m=true) for a in [0,100])... )`
image
becomes
image

Fixes #50

### CODE REVIEW

File: src/adapted_grid.jl [hunk 1]
```diff
@@ -119,10 +120,7 @@ function adapted_grid(f, minmax::Tuple{Real, Real}; max_recursions = 7)
                 end
             else
                 new_xs[i + k] = xs[i]
-                # Don't evaluate function at end points
-                if !(i == 1 || i == n_points)
-                    new_fs[i + k] = fs[i]
-                end
+                new_fs[i + k] = fs[i]
```
Comment (yha) [inline src/adapted_grid.jl]: The end points have `NaN` values which should propagate. Otherwise they remain zero, which messes up the scaling.

**Comment by mkborregaard** [comment]
Great!
